import Head from "next/head";
import Image from "next/image";

import {
  AiFillCheckCircle,
  AiFillGithub,
  AiFillLinkedin,
  AiFillMinusCircle,
  AiFillTwitterCircle,
} from "react-icons/ai";

import WavingHand3DEmoji from "../../public/waving-hand-3D-emoji.png";
import good from "../../public/good.png";
import best from "../../public/best.png";
import okay from "../../public/okay.png";
import project1 from "../../public/project1.png";
import project2 from "../../public/project2.png";
import project3 from "../../public/project3.png";
import project4 from "../../public/project4.png";
import project5 from "../../public/project5.png";
import project6 from "../../public/project6.png";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Shayan Ameen - JavaScript Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="mb-12 flex justify-between py-10 dark:text-white">
            <h1 className="font-burtons text-xl">shayan ameen</h1>
            <ul className="flex items-center">
              <li>
                <a
                  className="text- ml-8 rounded-md border-none bg-gradient-to-r from-cyan-500 to-teal-500 px-4 py-2 text-white"
                  href="#portfolio"
                >
                  Projects
                </a>
              </li>
            </ul>
          </nav>
          <div className="p-10 py-10 text-center">
            <h2 className="py-2 text-5xl font-medium text-teal-600 dark:text-teal-400 md:text-6xl">
              Shayan Ameen
            </h2>
            <h3 className="py-2 text-2xl dark:text-white md:text-3xl">
              JavaScirpt Developer.
            </h3>
            <p className="text-md mx-auto max-w-xl py-5 leading-8 text-gray-800 dark:text-gray-200 md:text-xl">
              Freelancer providing services for web developmet and marketing
              needs. Join me down below and let&apos;s get cracking!
            </p>
            <div className="flex justify-center gap-16 py-3 text-5xl text-gray-600 dark:text-gray-400">
              <AiFillGithub />
              <AiFillTwitterCircle />
              <AiFillLinkedin />
            </div>
            <div className="relative mx-auto mt-20 h-56 w-56 overflow-hidden rounded-full bg-gradient-to-b from-teal-500 md:h-96 md:w-96">
              <Image
                className="object-cover"
                src={WavingHand3DEmoji}
                alt="deved"
                fill
              />
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="py-1 text-3xl dark:text-white ">Services I offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a freelance designer and
              developer, I&apos;ve done remote work for
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talented people to provide digital services
              for both businesses and consumers.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including web design, web
              development and marketing.
            </p>
          </div>
          <ul className="gap-10 lg:flex">
            <li className="my-10 flex-1 rounded-xl p-10 shadow-lg dark:bg-gray-700">
              <div className="text-center">
                <Image className="mx-auto h-24 w-24" src={okay} alt="okay" />
                <h3 className="pt-8 pb-2 text-lg font-medium dark:text-white">
                  Silver Package
                </h3>
              </div>
              <h4 className="py-4 text-teal-500">What&apos;s Included</h4>
              <ul>
                <li className="flex items-center gap-4">
                  <AiFillCheckCircle className="text-6xl text-teal-500" />
                  <p className="py-2 dark:text-gray-300">
                    Creating elegant designs suited for your needs & following
                    core design theory.
                  </p>
                </li>
                <li className="flex items-center gap-4">
                  <AiFillMinusCircle className="text-6xl text-gray-500" />
                  <p className="py-2 dark:text-gray-300">
                    Do you have an idea for your next great project? Let&apos;s
                    make it a reality.
                  </p>
                </li>
                <li className="flex items-center gap-4">
                  <AiFillMinusCircle className="text-6xl text-gray-500" />
                  <p className="py-2 dark:text-gray-300">
                    Are you interested in marketing for your project? I can do
                    tricks to level it up.
                  </p>
                </li>
              </ul>
            </li>
            <li className="my-10 flex-1 rounded-xl p-10 shadow-lg dark:bg-gray-700">
              <div className="text-center">
                <Image className="mx-auto h-24 w-24" src={good} alt="good" />
                <h3 className="pt-8 pb-2 text-lg font-medium dark:text-white">
                  Gold Package
                </h3>
              </div>
              <h4 className="py-4 text-teal-500">What&apos;s Included</h4>
              <ul>
                <li className="flex items-center gap-4">
                  <AiFillCheckCircle className="text-6xl text-teal-500" />
                  <p className="py-2 dark:text-gray-300">
                    Creating elegant designs suited for your needs & following
                    core design theory.
                  </p>
                </li>
                <li className="flex items-center gap-4">
                  <AiFillCheckCircle className="text-6xl text-teal-500" />
                  <p className="py-2 dark:text-gray-300">
                    Do you have an idea for your next great project? Let&apos;s
                    make it a reality.
                  </p>
                </li>
                <li className="flex items-center gap-4">
                  <AiFillMinusCircle className="text-6xl text-gray-500" />
                  <p className="py-2 dark:text-gray-300">
                    Are you interested in marketing for your project? I can do
                    tricks to level it up.
                  </p>
                </li>
              </ul>
            </li>
            <li className="my-10 flex-1 rounded-xl p-10 shadow-lg dark:bg-gray-700">
              <div className="text-center">
                <Image className="mx-auto h-24 w-24" src={best} alt="best" />
                <h3 className="pt-8 pb-2 text-lg font-medium dark:text-white">
                  Platinum Package
                </h3>
              </div>
              <h4 className="py-4 text-teal-500">What&apos;s Included</h4>
              <ul>
                <li className="flex items-center gap-4">
                  <AiFillCheckCircle className="text-6xl text-teal-500" />
                  <p className="py-2 dark:text-gray-300">
                    Creating elegant designs suited for your needs & following
                    core design theory.
                  </p>
                </li>
                <li className="flex items-center gap-4">
                  <AiFillCheckCircle className="text-6xl text-teal-500" />
                  <p className="py-2 dark:text-gray-300">
                    Do you have an idea for your next great project? Let&apos;s
                    make it a reality.
                  </p>
                </li>
                <li className="flex items-center gap-4">
                  <AiFillCheckCircle className="text-6xl text-teal-500" />
                  <p className="py-2 dark:text-gray-300">
                    Are you interested in marketing for your project? I can do
                    tricks to level it up.
                  </p>
                </li>
              </ul>
            </li>
          </ul>
        </section>
        <section id="portfolio" className="py-10">
          <div>
            <h3 className="py-1 text-3xl dark:text-white ">Portofolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a freelance designer and
              dev7loper, I&apos;ve done remote work for
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talanted people to provide digital services
              for both businesses and consumers.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including web design, web
              development and marketing.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="flex-1 basis-1/3 ">
              <Image
                className="h-full w-full rounded-lg object-cover"
                src={project1}
                alt="project1"
              />
            </div>
            <div className="flex-1 basis-1/3">
              <Image
                className="h-full w-full rounded-lg object-cover"
                src={project2}
                alt="project2"
              />
            </div>
            <div className="flex-1 basis-1/3">
              <Image
                className="h-full w-full rounded-lg object-cover"
                src={project3}
                alt="project3"
              />
            </div>
            <div className="flex-1 basis-1/3">
              <Image
                className="h-full w-full rounded-lg object-cover"
                src={project4}
                alt="project4"
              />
            </div>
            <div className="flex-1 basis-1/3">
              <Image
                className="h-full w-full rounded-lg object-cover"
                src={project5}
                alt="project4"
              />
            </div>
            <div className="flex-1 basis-1/3">
              <Image
                className="h-full w-full rounded-lg object-cover"
                src={project6}
                alt="project6"
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
